image: node:14-slim

stages:
  - test
  - build

before_script:
  - npm install
  - npm install -g @angular/cli less
  - echo "//kexus.kodality.com/repository/npm/:_authToken=$NEXUS_NPM_TOKEN" > ~/.npmrc
  - echo "@kodality-web:registry=https://kexus.kodality.com/repository/npm/" >> ~/.npmrc

test:
  stage: test
  script:
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/chrome.list
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - apt-get update && apt-get install -y google-chrome-stable bash
    - npm run test-ci
  only:
    - main

snapshot:
  stage: build
  script:
    - npm run build
    - npm run publish
  only:
    - main


release:
  stage: build
  script:
    - export PACKAGE_VERSION="$CI_COMMIT_TAG"
    - npm run build
    - npm run publish $PACKAGE_VERSION
  only:
    - /^r\d*\.\d*\.\d*$/
  except:
    - branches
