image: node:14-slim

stages:
  - build
  - publish

before_script:
  - npm install
  - npm install -g @angular/cli less
  - echo "//kexus.kodality.com/repository/npm/:_authToken=$NEXUS_NPM_TOKEN" > ~/.npmrc
  - echo "@kodality-web:registry=https://kexus.kodality.com/repository/npm/" >> ~/.npmrc

build:
  stage: build
  script:
    - npm run build


release_snapshot:
  stage: publish
  script:
    - npm run publish
  only:
    - main


release_version:
  stage: publish
  script:
    - export PACKAGE_VERSION="CI_COMMIT_TAG"
  only:
    - /^r\d*\.\d*\.\d*$/
  except:
    - branches
