image: registry.gitlab.com/kodality/gitlab-builders/ng:20

cache:
  key:
    files:
      - package-lock.json
  policy: pull-push
  paths:
    - .npm/
    - node_modules/

stages:
  - build

before_script:
  - echo "//kexus.kodality.com/repository/npm/:_authToken=$NEXUS_NPM_TOKEN" > ~/.npmrc
  - echo "@kodality-web:registry=https://kexus.kodality.com/repository/npm/" >> ~/.npmrc


build:
  stage: build
  script:
    - npm install
    - npm run test:ci
    - npm run build
  only:
    - branches
  except:
    - /^\d*\.\d*.x$/


.publish_base:
  script:
    - npm install
    - npm run test:ci
    - npm run build
    - npm run publish ${VERSION}

snapshot_release:
  extends: .publish_base
  stage: build
  only:
    - /^\d*\.\d*.x$/

version_release:
  extends: .publish_base
  stage: build
  variables:
    VERSION: $CI_COMMIT_TAG | xargs
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d*\.\d*.\d*$/
      when: on_success
    - when: never
