name: Publish packages to GitHub Packages
on:
  push:
    branches: [ "main", "20.0.x" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            core-util:
              - 'core-util/package.json'
            ui:
              - 'ui/package.json'
            util:
              - 'util/package.json'
            quill:
              - 'quill/package.json'
            markdown:
              - 'markdown/package.json'
            markdown-parser:
              - 'markdown-parser/package.json'
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@termx-health'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish core-util
        if: steps.filter.outputs.core-util == 'true'
        working-directory: dist/core-util
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish ui
        if: steps.filter.outputs.ui == 'true'
        working-directory: dist/ui
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish util
        if: steps.filter.outputs.util == 'true'
        working-directory: dist/util
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish quill
        if: steps.filter.outputs.quill == 'true'
        working-directory: dist/quill
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish markdown-parser
        if: steps.filter.outputs.markdown-parser == 'true'
        working-directory: dist/markdown-parser
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish markdown
        if: steps.filter.outputs.markdown == 'true'
        working-directory: dist/markdown
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
