name: Publish package to GitHub Packages
on:
  push:
    branches: [ "main", "20.0.x" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            package:
              - 'core-util/package.json'
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kodality-web'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        if: steps.filter.outputs.package == 'true'
        working-directory: dist/core-util
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
